package:
  name: rasterstats
  version: "0.11.0"

source:
  fn: rasterstats-0.11.0.tar.gz
  url: https://pypi.python.org/packages/55/65/7376e111563ce13bc643e812728a2856a84614d42ba110fecbb8cf6ba88b/rasterstats-0.11.0.tar.gz
  md5: 8280338bd93f04655d89168258b5ed2f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rasterstats = rasterstats:main
    #
    # Would create an entry point called rasterstats that calls rasterstats.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson

  run:
    - python
    - setuptools
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson

test:
  # Python imports
  imports:
    - rasterstats

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - pyshp >=1.1.4
    - pytest
    - pytest-cov >=2.2.0
    - simplejson
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD License
  summary: 'Summarize geospatial raster datasets based on vector geometries'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
